### ISSUE TITLE
Programos instaliavimo klaida

### ISSUE THREAD

**Issue by Friebay** [valdas-v1/scrape_aruodas#1]
Sveiki.
Norėjau išsibandyti kodą „As a Standalone Script“ būdu, tačiau gavau klaidą 4-ame žingsnyje.
![image](https://github.com/valdas-v1/scrape_aruodas/assets/81957605/e8c38f03-02ad-4c19-838f-e15409ab83bf)
Ši klaida atsirado, nes „requirements.txt“ yra „scrape_aruodas“ aplanke, o ne bendrame aplanke, kuriame yra virtuali erdvė. Nurodžius aplanką, bibliotekos atsisiunčia.
Pull request nedarau, kad nerodytų prie contributors ar kaip ten, na, kad rodytų kad tik jūsų kodas. 😄

**Comment by valdas-v1** [comment]
README updated.
